<a href="https://colab.research.google.com/github/quangnhat1395/python-dataviz-course/blob/master/Tuan3_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ở trong phần này chúng ta sẽ làm quen với thư viện numpy, đồng thời tìm hiểu một số thao tác với dataFrame.

#Làm quen thư viện `numpy`

## Cài đặt
Ta có thể cài đặt `numpy` thông qua trình quản lý `pip` của Python như sau:

In [ ]:
pip install numpy

##Sử dụng
Để sử dụng thư viện `numpy`, ta tiến hành import nó vào, tương tự như các thư viện khác như sau:

In [ ]:
import numpy as np


## Mảng (array) trong numpy

Thư viện numpy chủ yếu được sử dụng để tính toán trên các dữ liệu kiểu mảng. Nôm na có thể hiểu, đây là dữ liệu có dạng vecto n chiều.

Ta thử tạo một mảng đơn giản bằng numpy như sau:

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
#kiem tra kich co cua mang a
print(a.shape)
print(a)

(3,)
[1 2 3]


Ta có thể hình dung quá trình trên như hình dưới đây:

![Untitled.png](https://2.pik.vn/202000257f8a-7bf1-460a-b51d-485e4d96df81.png)


Các lệnh trong numpy có nét tương đồng với matlab. Bạn đọc có thể tìm hiểu thêm ở [đây](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html). Ở bài viết này, chúng tôi chỉ sơ lược một vài lệnh cơ bản hay được sử dụng trong numpy.

In [ ]:
np.zeros(2) #Tao vecto  co 2 phan tu deu la 0
print(np.zeros(2))

[0. 0.]


In [ ]:
 np.ones(2) #tao vecto co 2 phan tu deu la 1
 print( np.ones(2))

[1. 1.]


In [ ]:
np.arange(4)# tao vecto tu 0-->3 (tuong ung voi lenh range)
print(np.arange(4))
np.arange(2, 9, 2)
print(np.arange(2, 9, 2))

[0 1 2 3]
[2 4 6 8]


In [ ]:
np.linspace(0, 10, num=5)#Tao vecto tu 0-->10 voi khoang cach bang nhau

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64) #ep kieu du lieu tu thuc-->nguyen
print(x)

[1 1]


In [ ]:
a = np.array([1, 2, 3])
print(a[0]) #Lay ra phan tu dau tien cua mang

1


## Thêm, bớt, sắp xếp các phần tử trong mảng
Để thêm, bớt hoặc sắp xếp các phần tử trong numpy, ta tiến hành như sau:

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) #mang ban dau
print(arr)
np.sort(arr) #Sap xep tang dan

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b)) #Ghep 2 mang lai

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Thay đổi kích cỡ mảng


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('Ma tran da cho co',a.shape[0], 'dong', a.shape[1], 'cot')

[[1 2 3]
 [4 5 6]]
Ma tran da cho co 2 dong 3 cot


Ta sẽ trải phẳng ma trận đã cho thành ma trận bằng lệnh `ravel()` như sau:

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

Hoặc ta có thể thay đổi sang dạng ma trận với số dòng, số cột khác bằng lệnh `reshape` như sau:

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Ngoài ra, ta có thể sử dụng lệnh `resize` như sau:

In [ ]:
print('ma tran ban dau\n', a)
a.resize((2,3))
print('ma tran sau khi bien doi\n', a)


ma tran ban dau
 [[1 2 3]
 [4 5 6]]
ma tran sau khi bien doi
 [[1 2 3]
 [4 5 6]]


Ta có thể sử dụng lệnh `a.T` để tạo ma trận chuyển vị của ma trận a như sau:


In [ ]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Chỉ số trong numpy

In [ ]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


Ta có thể minh hoạ các lệnh trên như hình dưới đây.

![11.png](https://2.pik.vn/20209565fee9-392d-4952-b12f-a721ff7e962d.png)



Ngoài ra, ta có thể lọc các phần tử thoả mãn một yêu cầu nào đó. Cụ thể như sau:

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [ ]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


## Ma trận trong numpy
Trong numpy, ta cũng làm việc với ma trận y như một vector nhiều chiều. Cụ thể như sau:


In [ ]:
# Tao ma tran
data = np.array([[1, 2], [3, 4]])

![11.png](https://2.pik.vn/202035becd37-33e6-41ce-a8ac-e9a3e065ef0b.png)

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


![222.png](https://2.pik.vn/202043855f10-dfb9-491c-8623-f108daf168ff.png)

In [ ]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


![222.png](https://2.pik.vn/202018a3cc82-5a62-48bf-af66-f9b3597ad788.png)

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 4, 6])

![333.png](https://2.pik.vn/20201b3d773c-dc66-411c-88be-193ad70beb36.png)


In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

![333.png](https://2.pik.vn/2020cdeeccea-65bb-4e47-a65d-209c84328b3a.png)

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![333.png](https://2.pik.vn/20204f55a0c7-b867-41cf-a92d-232622be3f35.png)

# Các thao tác với DataFrame



## Sắp xếp 
Trong pandas, ta có thể sắp xếp dataFrame bằng lệnh `df.sort_values`, cụ thể như sau:

In [ ]:
# Tao dataFrame
import pandas as pd
 
cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000],
        'Year': [2015,2013,2018,2018]
        }
 
df = pd.DataFrame(cars, columns= ['Brand', 'Price','Year'])

print (df)

            Brand  Price  Year
0     Honda Civic  22000  2015
1  Toyota Corolla  25000  2013
2      Ford Focus  27000  2018
3         Audi A4  35000  2018


In [ ]:
#Sap xep tang dan theo Brand
df.sort_values(by=['Brand'], inplace=True)
print(df)

            Brand  Price  Year
3         Audi A4  35000  2018
2      Ford Focus  27000  2018
0     Honda Civic  22000  2015
1  Toyota Corolla  25000  2013


In [ ]:
#Sap xep giam dan theo brand
df.sort_values(by=['Brand'], inplace=True, ascending=False)
print(df)

            Brand  Price  Year
1  Toyota Corolla  25000  2013
0     Honda Civic  22000  2015
2      Ford Focus  27000  2018
3         Audi A4  35000  2018


In [ ]:
#Sap xep theo nhieu bien
df.sort_values(by=['Year','Price'], inplace=True)
print(df)

            Brand  Price  Year
1  Toyota Corolla  25000  2013
0     Honda Civic  22000  2015
2      Ford Focus  27000  2018
3         Audi A4  35000  2018


## Mean
Ta có thể sử dụng lệnh `mean()` để tính giá trị mean của một dataFrame, cụ thể như sau:

In [ ]:
print(df.mean())

Price    27250.0
Year      2016.0
dtype: float64


## Độ lệch chuẩn
Để tính độ lệch chuẩn của một dataFrame, ta sử dụng lệnh `std()`, cụ thể như sau:

In [ ]:
print(df.std())

NameError: ignored

## Min max trong dataFrame


In [ ]:
print(df.min())

Brand    Audi A4
Price      22000
Year        2013
dtype: object


In [ ]:
print(df.max())

Brand    Toyota Corolla
Price             35000
Year               2018
dtype: object


## Median trong dataFrame

In [ ]:
print(df.median())

Price    26000.0
Year      2016.5
dtype: float64


## Correlation trong dataFrame

In [ ]:
print(df.corr())

          Price      Year
Price  1.000000  0.660801
Year   0.660801  1.000000


#Function trong Python
Trong Python, ta sử dụng `def` để định nghĩa một `function`. Để gọi hàm, ta chỉ việc gọi tên hàm. Cụ thể như sau:

In [2]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


## Tham số trong function
Ta có thể truyền một hoặc nhiều tham số vào trong `function` thông qua dấu ngoặc đơn. Cụ thể, cú pháp là:


```
def ten_ham(tham_so):
  Cau_lenh_trong_ham
```
Ta có thể xem xét ví dụ dưới đây:


In [4]:
def my_function(fname):
  print(fname + "An")

my_function("Tran ")
my_function("Nguyen ")
my_function("Le ") 

Tran An
Nguyen An
Le An


Hoặc function tính tổng của 2 số cho trước như sau:


In [6]:
def tong(a, b):
  print("Tong cua 2 so da cho la: ",a+b)

tong(2, 3)

Tong cua 2 so da cho la:  5


##Tham số bất kỳ
Trong trường hợp ta không biết chính xác số lượng tham số truyền vào (chẳng hạn, tính tổng các phần tử của một vector) ta có thể sử dụng dấu `*` trước tham số chưa xác định số phần tử.

Ta xem xét ví dụ dưới đây:

In [8]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus") 



The youngest child is Linus


Ngoài ra, ta có thể gán trực tiếp giá trị vào tham số trong trường hợp số tham số chưa biết bằng dấu `**` như sau:

In [9]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes") 

His last name is Refsnes


## Tham số mặc định
Ta có thể truyền các giá trị mặc định cho tham số trong trường hợp không nhận được giá trị cụ thể. Chẳng hạn, xét ví dụ dưới đây:

In [10]:
def my_function(country = "Sai Gon"):
  print("I am from " + country)

my_function("Ha Noi")
my_function()
my_function("Da Nang") 

I am from Ha Noi
I am from Sai Gon
I am from Da Nang


## Kiểu dữ liệu của tham số
Trong Python, ta có thể truyền vào tham số với bất kỳ kiểu dữ liệu nào. Chẳng hạn, ta có thể truyền vào một list như sau:

In [11]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


## Lệnh return 
Trong Python, ta sử dụng lệnh `return` để hàm trả về một giá trị cụ thể. Chẳng hạn, xét function dưới đây:

In [12]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9)) 

15
25
45


## Lệnh `pass`
Mặc định, trong Python function không được để trống. Tuy nhiên, vì nhiều lý do, ta có thể sử dụng lệnh `pass` trong function để lách luật. Cụ thể như sau:

In [13]:
def myfunction():
  pass

## Lambda function

Lambda function là một hàm ẩn danh có dạng rút gọn với cú pháp như sau:


```
lambda tham_so : cau_lenh
```
Cụ thể, ta xét ví dụ sau:





In [14]:
x = lambda a : a + 10

print(x(5)) 

15


In [15]:
x = lambda a, b : a * b

print(x(5, 6)) 

30


#Bài tập

1. Nhập vào một vector, xuất ra tất cả các phần tử chẵn của vector đó.

2. Nhập vào một vector, thay thế các phần tử chẵn bằng giá trị -1

3. Nhập vào một vector có $2n$ phần tử, $\ n \in \mathbb{N}^*$ . Chuyển vector trên thành ma trận có 2 cột.

4. Nhập vào 2 vector, xuất ra các phần tử chung của 2 vector đó.

5. Nhập vào 2 ma trận $A, B$. Xuất ra các ma trận $A+B, AB, A-B, A/B$.

6. Nhập vào bộ dữ liệu Iris, tính 